/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
package org.zeromq.zyre

import kotlin.test.Test

class ZyreEventTest {

    @Test
    fun test() {
        ZyreEvent.test(false)
    }

}
