/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/

plugins {
    alias(libs.plugins.nexusPublish)
    alias(libs.plugins.androidLibrary).apply(false)
    alias(libs.plugins.kotlinMultiplatform).apply(false)
}

allprojects {
    group = "org.zeromq.zyre"

    if (project.hasProperty("isRelease")) {
        version = "2.0.1"
    } else {
        version = "2.0.1-SNAPSHOT"
    }
}

nexusPublishing {
    // Configure maven central repository
    // https://github.com/gradle-nexus/publish-plugin#publishing-to-maven-central-via-sonatype-ossrh
    repositories {
        sonatype {  //only for users registered in Sonatype after 24 Feb 2021
            nexusUrl.set(uri("https://s01.oss.sonatype.org/service/local/"))
            snapshotRepositoryUrl.set(uri("https://s01.oss.sonatype.org/content/repositories/snapshots/"))
        }
    }
}

//project.gradle.taskGraph.whenReady { TaskExecutionGraph taskGraph ->
//    if (System.getenv("GRADLE_VERBOSE") == "1") {
//        Task execTask = taskGraph.allTasks.last()
//        println("Task plan for '${execTask.project.name}:${execTask.name}'")
//        taskGraph.allTasks.eachWithIndex { Task task, int n ->
//            println "${String.format("%3s", n + 1)} - '${task.project.name}:${task.name}'"
//        }
//    }
//}

