/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/

import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    `maven-publish`
    signing
}

val dependenciesVersion =
    if (project.hasProperty("isRelease"))
        "latest.release"
    else
        "latest.integration"

kotlin {
    targetHierarchy.default()

    jvm {
    }
    androidTarget {
        publishLibraryVariants("release")
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_1_8)
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation("org.zeromq.czmq:czmq:$dependenciesVersion")
            }
        }
        commonTest {
            dependencies {
                implementation(libs.kotlinTest)
            }
        }
        jvmMain {
            resources.srcDir("nativeLibs")
            dependencies {
                implementation(libs.jna)
            }
        }
        jvmTest {
            dependencies {
            }
        }
        androidMain {
            dependencies {
                // TODO: Android should use the @aar artifact type
                api(libs.jna)// {
//                artifact {
//                    type = "aar"
//                }
//            }
            }
        }
        androidUnitTest {
            dependencies {
            }
        }
    }
}

android {
    namespace = "org.zeromq.library"
    compileSdk = 34
    defaultConfig {
        minSdk = 21
    }
}

publishing {
    publications.withType<MavenPublication> {
        // Stub javadoc.jar artifact
        artifact(tasks.register("${name}JavadocJar", Jar::class) {
            archiveClassifier.set("javadoc")
            archiveAppendix.set(this@withType.name)
        })

        // Provide artifacts information required for publication
        pom {
            name.set("zyre")
            description.set("an open-source framework for proximity-based P2P apps")
            url.set("https://github.com/zeromq/zyre")

            licenses {
                license {
                    name.set("Mozilla Public License Version 2.0")
                    url.set("https://www.mozilla.org/en-US/MPL/2.0/")
                }
            }
            scm {
                connection.set("https://github.com/zeromq/zyre.git")
                developerConnection.set("https://github.com/zeromq/zyre.git")
                url.set("https://github.com/zeromq/zyre")
            }
        }
    }
}

signing {
//    if (project.hasProperty("signing.gnupg.keyName")) {
//        useGpgCmd()
//        sign(publishing.publications)
//    }
}

